<?php

/**
 * @file
 * Allows users to create membership entities.
 */

/**
 * Implements hook_help().
 */
function memberships_help($path, $arg) {
  switch ($path) {
    case 'admin/config/meberships/settings':
      return '<p>' . t('This page provides general settings for memberships on your website.') . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function memberships_permission() {
  return array(
    'adminster memberships' => array(
      'title' => t('Administer Memberships'),
      'description' => t('Perform administration tasks for memberships.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function memberships_menu() {
  $items = array();

  $items['admin/config/memberships/settings'] = array(
    'title' => 'Membership settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('membership_admin_settings_form'),
    'access arguments' => array('administer memberships'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'memberships.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function memberships_admin_paths() {
  return array(
    'admin/config/memberships/*' => TRUE,
  );
}
